Update CSP documentation to clarify availability of the CSP build
alpinejs/alpine pull request #2619
Opened 2022-01-27 23:47 UTC by thibaudcolas

As a newcomer considering Alpine.js for a project, I found it very confusing that the CSP build’s documentation makes it sound like it’s available to use now even though it’s not. This PR makes minimal changes to the page to clarify this, and provide guidance on what people should do in the meantime.

The info I added is based on https://github.com/alpinejs/alpine/issues/237#issuecomment-999692410 – there might be more details that could be added here that aren’t publicly available (see also https://github.com/alpinejs/alpine/discussions/1944).

2022-01-28 00:16 UTC, Darkle requested changes

2022-01-28 00:16 UTC, Darkle commented on packages/docs/src/en/advanced/csp.md
> +The CSP build hasn’t been officially released yet. In the meantime, you may [build it from source](https://github.com/alpinejs/alpine/tree/main/packages/csp). Once released, ike all Alpine extensions
Misspelling: `ike` should be `like`

2022-03-03 21:51 UTC, MichaelMackus commented
I wonder if there's a way we can help get this included in NPM. It would be very handy to have an NPM-installable version of the CSP build.

2022-08-19 17:08 UTC, plasid commented
Love AlpineJs!!, and migrating some of our Vue apps to Alpine. Do you guys have any indication of when the CSP version will be NPM installable?

2022-11-23 22:12 UTC, joshhanley commented
Currently the CSP build is unfinished, hence why it's not available on NPM. We're going to leave this open for now, as we'd prefer to get the build finished.

2022-12-08 14:11 UTC, thibaudcolas commented
@joshhanley thank you for taking a look at this, good to know where Alpine maintainers stand.

Could you reconsider what happens with this PR? It’s completely fine for the CSP build to not exist, but until it does the issue of the documentation being misleading is still a thing. That’s the only thing this PR addresses, and the changes I made here should be pretty straightforward to include now, and later revert once the build gets finished.

2022-12-08 22:30 UTC, joshhanley commented
@thibaudcolas yep, I understand and agree. I'm just passing on Caleb's feedback 🙂

I will see if he will approve of me merging this anyway.

2023-01-28 00:25 UTC, merged

2023-01-28 00:26 UTC, joshhanley commented
@thibaudcolas got permission to merge, thanks for the PR! 🙂

2023-02-23 16:15 UTC, thibaudcolas commented
@joshhanley nice one! Just so you know, the contents of the live site at https://alpinejs.dev/advanced/csp are still showing the previous version.

2023-03-05 23:09 UTC, joshhanley commented
@thibaudcolas thanks, yeah it doesn't get released until a new version of Alpine is tagged. I've mentioned it to Caleb 🙂